### ISSUE TITLE
httpparser + nbio 实现http server基础功能

### ISSUE THREAD

**Issue by lesismal** [antlabs/httparser#4]
如果只是为了轻便的网络层，libev的API形式没什么必要，或者如果你喜欢，可以简单在nbio基础上 wrap 一层
我写了个简单的 nbio + httpparser 的例子，httpparser 的 bug 我先忽略了，默认 httpparser.Execute 每次能解析成功一个请求，详见注释：

server.go
```golang
package main

import (
	"fmt"
	"log"
	"time"

	"github.com/antlabs/httparser"
	"github.com/lesismal/nbio"
)

var responseFormat = "HTTP/1.1 200 OK\r\n" +
	"Date: Tue, 02 Feb 2021 10:58:43 GMT\r\n" +
	"Content-Length: %v\r\n" +
	"Content-Type: text/plain; charset=utf-8\r\n" +
	"Connection: close\r\n\n%v"

// Request .
type Request struct {
	Headers map[string]string
	Body    []byte
}

// Session .
type Session struct {
	Parser    *httparser.Parser
	Setting   *httparser.Setting
	Request   *Request
	completed bool
}

// Next .
func (session *Session) Next() (*Request, bool) {
	if session.completed {
		return session.Request, true
	}
	return nil, false
}

func main() {
	g, err := nbio.NewGopher(nbio.Config{
		Network: "tcp",
		Addrs:   []string{":8080"},
	})
	if err != nil {
		log.Printf("nbio.New failed: %v\n", err)
		return
	}

	g.OnOpen(func(c *nbio.Conn) {
		c.SetReadDeadline(time.Now().Add(time.Second * 120))

		parser := httparser.New(httparser.REQUEST)
		setting := &httparser.Setting{
			MessageBegin: func() {
				session := c.Session().(*Session)
				session.Request = &Request{}
				session.completed = false
			},
			Body: func(buf []byte) {
				session := c.Session().(*Session)
				session.Request.Body = append(session.Request.Body, buf...)
			},
			MessageComplete: func() {
				session := c.Session().(*Session)
				session.completed = true
			},
		}
		c.SetSession(&Session{Parser: parser, Setting: setting})

		log.Println("+ connected:", c.RemoteAddr().String(), time.Now().Format("15:04:05.000"))
	})

	g.OnClose(func(c *nbio.Conn, err error) {
		log.Println("- disconnected:", c.RemoteAddr().String(), time.Now().Format("15:04:05.000"), err)
	})

	g.OnData(func(c *nbio.Conn, data []byte) {
		c.SetReadDeadline(time.Now().Add(time.Second * 120))

		session := c.Session().(*Session)

		// 这里忽略了 httpparser 解析的bug，先默认认为解析成功
		_, err := session.Parser.Execute(session.Setting, data)
		if err != nil {
			log.Printf("parse failed: %v", err)
			c.Close()
			return
		}

		c.SetWriteDeadline(time.Now().Add(time.Second * 3))
		response := append([]byte(fmt.Sprintf(responseFormat, len(session.Request.Body), string(session.Request.Body))))
		c.Write(response)

		// Parser.Execute 应该是这样子更合理
		// for {
		// 	request, ok, err := session.Parser.Execute(session.Setting, data)
		// 	if err != nil {
		// 		log.Printf("parse failed: %v", err)
		// 		c.Close()
		// 		return
		// 	}
		// 	if ok {
		// 		c.SetWriteDeadline(time.Now().Add(time.Second * 3))
		// 		c.Write(responseData)
		// 	} else {
		// 		break
		// 	}
		// }
	})

	err = g.Start()
	if err != nil {
		log.Printf("nbio.Start failed: %v\n", err)
		return
	}

	// go func() {
	// 	for {
	// 		time.Sleep(time.Second * 5)
	// 		log.Println(g.State().String())
	// 	}
	// }()

	g.Wait()
}
```

client.go
```golang
package main

import (
	"fmt"
	"io/ioutil"
	"net/http"
	"strings"
	"time"
)

func main() {
	url := "http://localhost:8080/echo"
	method := "POST"
	client := &http.Client{}

	for i := 0; i < 10; i++ {
		payload := strings.NewReader("hello")
		req, err := http.NewRequest(method, url, payload)
		if err != nil {
			fmt.Println(111, err)
		}
		res, err := client.Do(req)
		if err != nil {
			fmt.Println(222, err)
			return
		}
		defer res.Body.Close()
		body, err := ioutil.ReadAll(res.Body)

		fmt.Println("body:", string(body))

		time.Sleep(time.Second / 10)
	}
}
```

**Comment by guonaihong** [comment]
解析器，我提个issue，重新优化内部的状态机。

**Comment by guonaihong** [comment]
我先参考你的demo。我打算先实现一个wrk。看看性能。

**Comment by lesismal** [comment]
> 我先参考你的demo。我打算先实现一个wrk。看看性能。

好的

单纯作为网络层的话，nbio不需要什么修改了，但是没商业项目测过，如果遇到nbio有bug，提issue给我

**Comment by guonaihong** [comment]
ok

**Comment by lesismal** [comment]
我把 nbio 加了下全平台的支持，windows、mac下也方便开发相关功能了
但是除了linux是epoll，其他平台是用的标准库的 net 包，没有用异步，每个连接一个协程，除非特殊情况单个连接的读写阻塞了、并且广播的场景里会有线头阻塞的问题，日常开发、调试时使用的效果跟用epoll差不多

还没合并master，platforms分支下做的支持:
https://github.com/lesismal/nbio/tree/platform

我是在前年看 xtaci 要写 gaio 时群里聊 golang 的异步网络库这块，当时大家对其他已有的开源都不满意，所以心血来潮也写了份，由于没有太多用户受众，暂时没考虑花太多时间做完善的工程细节，否则文档、注释、coverage、lint这些也都得搞一波，需要多花不少时间

**Comment by guonaihong** [comment]
ok。对了lesismal  ，xtaci在的群是微信群，还是qq群？这位大佬对传输时延很有研究，我打算看http3的时候和他讨论下。

**Comment by lesismal** [comment]
> ok。对了lesismal ，xtaci在的群是微信群，还是qq群？这位大佬对传输时延很有研究，我打算看http3的时候和他讨论下。

qq群，459420581

**Comment by lesismal** [comment]
稍微整理了下，全平台支持还是放到主分支了，platform分支删掉了，顺带review了下代码，又优化了一些小细节
以后有闲了我再多整理下文档示例之类的

**Comment by guonaihong** [comment]
ok。

**Comment by lesismal** [comment]
nbio的主要整理基本完成了，都已经放到 master 分支了

linux 压测了下性能应该也还是比其他的快一些，简单跑了下多核 pprof 对比了下 gev、gnet，read/write的syscall 占比，gev < gnet < nbio ，也就是说相同时间内，nbio的syscall 占比更高，而syscall的部分应用层是没法进一步优化了，所以 nbio 框架层的代码耗时更少些，我自己机器上的压测数据也略优于 gnet ，压测代码放下一楼里了

之前是打算用标准库net做windows和bsd的，但最近还是花时间把kqueue支持上了，但是由于手上没有mac，只能利用github actions或者travis，提交后由它们构建、跑test，基础的test是ok了的，但是macos下我没有进行大量的测试
windows是用的标准库的net，conn还是阻塞的，非windows则是非阻塞的，除了特殊状况导致单个连接窗口拥塞、影响广播场景下的其他连接，没有广播的其他场景上没什么影响，windows下不追求极致性能，主要方便日常开发
nbio.Conn实现了net.Conn（虽然是非阻塞），用起来更容易、方便，比如 SetDeadLline相关的

功能已经相对完善了，代码量也不多，跨平台加起来2000行以内，并且易用性应该是比其他那几个更好些的

**Comment by lesismal** [comment]
[loadtest.zip](https://github.com/antlabs/httparser/files/5986057/loadtest.zip)

**Comment by guonaihong** [comment]
ok。新年快乐。
我这两天看下代码。对了，你上面提到
> 除了特殊状况导致单个连接窗口拥塞、影响广播场景下的其他连接，没有广播的其他场景上没什么影响

这种情况需要在应用做公平性算法补偿吗？

**Comment by lesismal** [comment]
广播时的单个连接阻塞怎么补偿？
没法补偿

**Comment by lesismal** [comment]
for conn := range conns {
    // Write阻塞，应用层做不了
    conn.Write(...)
}

你说的补偿是单个连接情况下，或者业务层触发条件时、在Write之前的事情，跟网络库基础设施不在一个层面上

**Comment by guonaihong** [comment]
好像看xtaci也说过这个话题。我先记录到todo list+你的idea，有时间深度挖掘，等有些积累，再聊公平性话题。

**Comment by lesismal** [comment]
> 说过这个话题。我先记录到todo list+你的idea，有时间深度挖掘，等有些积累，再聊公

异步库不涉及这个，只是因为我的nbio为了支持win而用了std/net所以在win下仍然是阻塞的Conn，但定位主要是linux，win下面调试功能足够了，并且常规情况下也很难遇到这种问题

异步库的层面涉及的饿死的问题主要是event loop的每次loop中，如果个别Conn的数据量大，比如这个Conn一下子来了1M数据，然后你单次loop中处理这个连接并抛给应用层的过程中，解包每个协议只有百八十字节，1M对应上万个消息，其他连接的消息就要等你这个，这是饿死的问题
nbio在*nix下的单次event loop中单个连接最多读取readbuffer size，这个size是应用层可配置的，根据自己的业务需要，并且读数据、解析、业务层处理可以自己定制不同的上下游生产与消费关系，完全可以避免这种极端问题

**Comment by lesismal** [comment]
> 好像看xtaci也说过这个话题。我先记录到todo list+你的idea，有时间深度挖掘，等有些积累，再聊公平性话题。

群聊容易灌水，太浪费时间，我退群很久了，挺想念 xtaci 他们的

**Comment by lesismal** [comment]
这两天给 nbio 新增了tls支持，从头写太耗时间了，我干脆从标准库copy了一份出来，然后改成支持non-blocking的了，暂时只支持 tls 1.3 和 server-side，闲了再花时间支持 1.3 以下版本、client-side

所以，我又想到，标准库 http 也 copy+hack 一份算了。。。否则自己写 parser 还不够，还要很多细节支持，工程量太大。。

**Comment by guonaihong** [comment]
厉害厉害



---原始邮件---
发件人: "lesismal"<notifications@github.com&gt;
发送时间: 2021年2月21日(周日) 凌晨0:36
收件人: "antlabs/httparser"<httparser@noreply.github.com&gt;;
抄送: "guonaihong"<guonaihong@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [antlabs/httparser] httpparser + nbio 实现http server基础功能 (#4)




 
这两天给 nbio 新增了tls支持，从头写太耗时间了，我干脆从标准库copy了一份出来，然后改成支持non-blocking的了，暂时只支持 tls 1.3 和 server-side，闲了再花时间支持 1.3 以下版本、client-side
 
所以，我又想到，标准库 http 也 copy+hack 一份算了。。。否则自己写 parser 还不够，还要很多细节支持，工程量太大。。

**Comment by lesismal** [comment]
tls的例子放到这里了：
https://github.com/lesismal/nbio/tree/master/examples/tls

tls的hack，其他的异步库也可以用，但是依赖他们实现 net.Conn，作为 tls.Conn 的 under-layer

前年大概也是过年前后，最初写 nbio，没想写这么多，只是写来玩玩，当时还跟 xtaci 聊过，他说我 nbio.Conn 实现了 net.Conn 没什么必要
最近支持 tls，或者以后支持 http，看来是很有必要，算是无心插柳了，开心，哈哈哈

**Comment by lesismal** [comment]
TLS 1.0-1.3 server-side 今天都加上了，测试基本ok，TLS交互流程麻烦，全面测试覆盖有点耗时间，我先暂停了，等有人用发现bug了提issue我再改
client-side 暂时没什么必要，先缓缓，我先看看标准库 http 魔改成支持 non-blocking 难度大不 :joy:

**Comment by guonaihong** [comment]
哈哈，😄厉害。我这几天在找工作。等下个月稳定下来，就可以继续玩起。tls到时候也看下



---原始邮件---
发件人: "lesismal"<notifications@github.com&gt;
发送时间: 2021年2月22日(周一) 下午5:02
收件人: "antlabs/httparser"<httparser@noreply.github.com&gt;;
抄送: "guonaihong"<guonaihong@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [antlabs/httparser] httpparser + nbio 实现http server基础功能 (#4)




 
TLS 1.0-1.3 server-side 今天都加上了，测试基本ok，TLS交互流程麻烦，全面测试覆盖有点耗时间，我先暂停了，等有人用发现bug了提issue我再改
 client-side 暂时没什么必要，先缓缓，我先看看标准库 http 魔改成支持 non-blocking 难度大不 😂

**Comment by lesismal** [comment]
> 哈哈，厉害。我这几天在找工作。等下个月稳定下来，就可以继续玩起。tls到时候也看下
> […](#)
> ---原始邮件--- 发件人: "lesismal"<notifications@github.com&gt; 发送时间: 2021年2月22日(周一) 下午5:02 收件人: "antlabs/httparser"<httparser@noreply.github.com&gt;; 抄送: "guonaihong"<guonaihong@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [antlabs/httparser] httpparser + nbio 实现http server基础功能 (#4) TLS 1.0-1.3 server-side 今天都加上了，测试基本ok，TLS交互流程麻烦，全面测试覆盖有点耗时间，我先暂停了，等有人用发现bug了提issue我再改 client-side 暂时没什么必要，先缓缓，我先看看标准库 http 魔改成支持 non-blocking 难度大不  — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

good luck！
别找做底层开发这种职位，多数都不值钱、发展空间小
写业务虽然太easy，但是业务做多了可以往上做架构，架构能力牛逼了才值钱
